#!/usr/bin/env bash

ls source
ls ~/.ssh
git --version
chmod 400 ./source/id_rsa
cp ./source/config ~/.ssh/config
git clone git@github.com:ucsd-cse11-s20/${ASSIGNMENT_TITLE}-grading.git
rm ./source/id_rsa
cd ${ASSIGNMENT_TITLE}-grading
./grade
./run